cmake_minimum_required(VERSION 3.16)
project(cpp_agent_evaluation LANGUAGES CXX)
include(CTest)
find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(WORKSPACE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../workspace")
set(BENCH_TASK "all" CACHE STRING "Task to evaluate")
set(TASKS task-1-gol task-2-transformation task-3-rasterization task-4-raytracing)
if(BENCH_TASK STREQUAL "all")
  foreach(task IN LISTS TASKS)
    add_subdirectory(${task})
  endforeach()
elseif(BENCH_TASK IN_LIST TASKS)
  add_subdirectory(${BENCH_TASK})
else()
  message(FATAL_ERROR "Unknown BENCH_TASK: ${BENCH_TASK}")
endif()
